CREATE TABLE IF NOT EXISTS users(
    user_id SERIAL PRIMARY KEY,
	password TEXT NOT NULL,
	username TEXT UNIQUE NOT NULL
	);
CREATE TABLE IF NOT EXISTS posts(
	post_id SERIAL PRIMARY KEY,
	title TEXT NOT NULL,
	content TEXT NOT NULL,
	user_id SERIAL REFERENCES users(user_id) ON DELETE SET NULL, 
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
	);